### ISSUE TITLE
Chat embed crashes browser

### ISSUE THREAD

**Issue by EmersonGGS** [justintv/Twitch-API#499] opened 2016-02-12 17:33 UTC
The regex for emberchat.js (^https?:\/\/([a-zA-Z0-9]+.)*twitch.tv(:[0-9]+)?\/.*$) times out and crashes browsers with a lengthy url.

example url: https://someReallyLongUrl.someReallyLongUrl.com/someReallyLongUrl?someReallyLongUrl=someReallyLongUrl

 related: #492

**Comment by Argus9** [comment] 2016-02-14 23:20
Hey @EmersonGGS, glad you were able to discover the cause of this. That makes a lot of sense - my URL definitely gets lengthy the more streamers I display in the page.

**Comment by Argus9** [comment] 2016-02-15 15:54
Can confirm that shortening my URL when attempting to load the chat frame eliminates the browser crash.

**Comment by cjardine** [comment] 2016-02-18 16:19
This is a problem, not everyone has the option of simply shortening their url.

Here is an example of the code used by Twitch evaluating the scenario of the OP. Luckily the site where this is posted catches the error but you can see how it is unable to complete evaluating do to the poorly crafted expression.

[http://regexr.com/3cr1v](http://regexr.com/3cr1v)

**Comment by jzisserJg** [comment] 2016-02-18 16:58
@cjardine, agreed. And trying to shorten my site's URL comes with its own share of problems.

**Comment by Argus9** [comment] 2016-02-18 16:59
@cjardine, agreed. And shortening my site's URL creates its own problems.

**Comment by Fugiman** [comment] 2016-02-18 21:11
This was fixed on Feb 16th

**Closed by Fugiman** 2016-02-18 21:11 UTC
