### ISSUE TITLE
Bug: passing client_id parameter to the /streams endpoint returns an empty object.

### ISSUE THREAD

**Issue by codepoet** [justintv/Twitch-API#459] opened 2015-11-06 23:15 UTC
Description:
===========
When passing client_id parameter to the /streams endpoint the server returns an empty object. This behavior make the channel appear offline. 

Product: Twitch API             Version: 3
Date: 11-6-2015
Is it reproducible: Yes

Steps to Produce/Reproduce
--------------------------
> GET /streams?channel=bobross&client_id=[client_id]

Expected Results:
----------------
```
{
   "streams":[
      {
         "_id":17515457280,
         "game":"Creative",
         "viewers":46797,
         "created_at":"2015-11-06T07:42:46Z",
         "video_height":720,
         "average_fps":29.8408010373,
         "delay":0,
         "is_playlist":false,
         "_links":{
            "self":"https://api.twitch.tv/kraken/streams/bobross"
         },
         "preview":{
            "small":"http://static-cdn.jtvnw.net/previews-ttv/live_user_bobross-80x45.jpg",
            "medium":"http://static-cdn.jtvnw.net/previews-ttv/live_user_bobross-320x180.jpg",
            "large":"http://static-cdn.jtvnw.net/previews-ttv/live_user_bobross-640x360.jpg",
            "template":"http://static-cdn.jtvnw.net/previews-ttv/live_user_bobross-{width}x{height}.jpg"
         },
         "channel":{
            "mature":false,
            "status":"The Joy of Painting Marathon - Celebrating the official launch of Twitch Creative! #painting #oilpaint #bobross",
            "broadcaster_language":"en",
            "display_name":"BobRoss",
            "game":"Creative",
            "language":"en",
            "_id":105458682,
            "name":"bobross",
            "created_at":"2015-10-28T16:13:41Z",
            "updated_at":"2015-11-06T21:15:55Z",
            "delay":null,
            "logo":"http://static-cdn.jtvnw.net/jtv_user_pictures/bobross-profile_image-0b9dd167a9bb16b5-300x300.jpeg",
            "banner":null,
            "video_banner":"http://static-cdn.jtvnw.net/jtv_user_pictures/bobross-channel_offline_image-802f2cbaf5b9811d-1920x1080.png",
            "background":null,
            "profile_banner":null,
            "profile_banner_background_color":null,
            "partner":true,
            "url":"http://www.twitch.tv/bobross",
            "views":3321956,
            "followers":410269,
            "_links":{
               "self":"http://api.twitch.tv/kraken/channels/bobross",
               "follows":"http://api.twitch.tv/kraken/channels/bobross/follows",
               "commercial":"http://api.twitch.tv/kraken/channels/bobross/commercial",
               "stream_key":"http://api.twitch.tv/kraken/channels/bobross/stream_key",
               "chat":"http://api.twitch.tv/kraken/chat/bobross",
               "features":"http://api.twitch.tv/kraken/channels/bobross/features",
               "subscriptions":"http://api.twitch.tv/kraken/channels/bobross/subscriptions",
               "editors":"http://api.twitch.tv/kraken/channels/bobross/editors",
               "teams":"http://api.twitch.tv/kraken/channels/bobross/teams",
               "videos":"http://api.twitch.tv/kraken/channels/bobross/videos"
            }
         }
      }
   ],
   "_total":1,
   "_links":{
      "self":"https://api.twitch.tv/kraken/streams?channel=bobross&limit=25&offset=0",
      "next":"https://api.twitch.tv/kraken/streams?channel=bobross&limit=25&offset=25",
      "featured":"https://api.twitch.tv/kraken/streams/featured",
      "summary":"https://api.twitch.tv/kraken/streams/summary",
      "followed":"https://api.twitch.tv/kraken/streams/followed"
   }
}
```
Actual Results:
--------------
```
{
   "streams":[

   ],
   "_total":0,
   "_links":{
      "self":"https://api.twitch.tv/kraken/streams?channel=bobross&client_id=[client_id]&limit=25&offset=0",
      "next":"https://api.twitch.tv/kraken/streams?channel=bobross&client_id=[client_id]&limit=25&offset=25",
      "featured":"https://api.twitch.tv/kraken/streams/featured",
      "summary":"https://api.twitch.tv/kraken/streams/summary",
      "followed":"https://api.twitch.tv/kraken/streams/followed"
   }
}
```
Workarounds
-----------
pass the client_id parameter as a header or (not recommended) omit the client_id parameter all together until the bug is fixed.

> GET /streams/channel=bobross

**Comment by bashtech** [comment] 2015-11-06 23:17
Duplicate of #457

**Comment by Fugiman** [comment] 2015-11-07 11:03
As per [the documentation](https://github.com/justintv/Twitch-API/blob/master/v3_resources/streams.md#get-streams), this is expected behavior and not a bug.

**Closed by Fugiman** 2015-11-07 11:03 UTC
